<script lang="ts">
	import { LOCALES } from '$lib/i18n';
	import { m } from '$lib/paraglide/messages';

	/**
	 * The curated obligation register from doc 16 §5 — hand-authored, because it
	 * is the legally load-bearing half and no script can produce it. The
	 * per-dependency licence appendix is generated by `pnpm licenses:gen` in
	 * Week 8 and rendered below the marker at the bottom of this file.
	 *
	 * Item names and licence identifiers are proper nouns and stay untranslated;
	 * only the obligation column is a message. They live in this array rather
	 * than in the markup so they are expressions, not stray text nodes.
	 */
	const ROWS = [
		{ item: 'Open-Meteo', licence: 'CC BY 4.0', obligation: 'legal.licenses.ob_open_meteo' },
		{
			item: 'ExchangeRate-API',
			licence: 'free tier',
			obligation: 'legal.licenses.ob_exchangerate'
		},
		{ item: 'OpenStreetMap', licence: 'ODbL', obligation: 'legal.licenses.ob_osm' },
		{ item: 'OpenFreeMap', licence: 'free tiles', obligation: 'legal.licenses.ob_openfreemap' },
		{ item: 'Photon (komoot)', licence: 'Apache-2.0', obligation: 'legal.licenses.ob_photon' },
		{ item: 'Nominatim', licence: 'ODbL + policy', obligation: 'legal.licenses.ob_nominatim' },
		{
			item: 'Finnhub · Twelve Data · Binance · Stooq',
			licence: 'per ToS',
			obligation: 'legal.licenses.ob_markets'
		},
		{
			item: 'gridstack · ECharts · MapLibre · Dexie · Svelte · SvelteKit · Tailwind · marked · DOMPurify · music-metadata · Paraglide · fast-xml-parser',
			licence: 'MIT · Apache-2.0 · BSD-3',
			obligation: 'legal.licenses.ob_deps'
		},
		{
			item: 'Be Vietnam Pro · JetBrains Mono',
			licence: 'OFL 1.1',
			obligation: 'legal.licenses.ob_fonts'
		},
		{
			item: 'Hồ Ngọc Đức — âm lịch',
			licence: 'published algorithm',
			obligation: 'legal.licenses.ob_lunar'
		}
	] as const;
</script>

<svelte:head><title>{m['legal.licenses.page_title']()}</title></svelte:head>

{#each LOCALES as locale (locale)}
	<div data-locale={locale}>
		<h1>{m['legal.licenses.title'](undefined, { locale })}</h1>
		<p>{m['legal.licenses.intro'](undefined, { locale })}</p>

		<div class="tp-scroll">
			<table>
				<thead>
					<tr>
						<th>{m['legal.licenses.col_item'](undefined, { locale })}</th>
						<th>{m['legal.licenses.col_licence'](undefined, { locale })}</th>
						<th>{m['legal.licenses.col_obligation'](undefined, { locale })}</th>
					</tr>
				</thead>
				<tbody>
					{#each ROWS as row (row.item)}
						<tr>
							<td>{row.item}</td>
							<td>{row.licence}</td>
							<td>{m[row.obligation](undefined, { locale })}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>

		<p>{m['legal.licenses.deps_pending'](undefined, { locale })}</p>
	</div>
{/each}

<!-- licenses:gen insertion point — do not remove (doc 16 §5) -->
