import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

/** The message both music-metadata rules below give (doc 20 §7). */
const MAIN_THREAD =
	'music-metadata runs in the tag worker only: import it from widgets/music/tags.ts, and tags.ts only from tag-worker.ts (doc 20 §7).';
/** `./tags` from inside widgets/music, or any path ending in music/tags. */
const TAGS_MODULE = '^(\\./tags|.*/music/tags)$';

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `wrangler types` (pnpm gen). Not hand-edited, and it carries
	// its own eslint-disable directives that this config makes redundant.
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		rules: {
			// Positional snippet and callback parameters cannot be skipped, so a
			// leading underscore is how an unused one is declared deliberately —
			// `{#snippet failed(_error, reset)}` needs the first slot filled.
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			]
		}
	},
	// doc 20 §7: tag parsing happens in the worker, never on the main thread.
	// Nothing else enforces that: one value import from the wrong module would
	// pull ~63 KiB of music-metadata into a music chunk, and no budget row would
	// notice. So `music-metadata` may be imported by `tags.ts` alone, and
	// `tags.ts` (as a value) by the worker alone. Types are erased and stay free;
	// tests exercise both modules directly and are exempt.
	{
		files: ['src/**/*.{ts,svelte}'],
		ignores: [
			'src/lib/widgets/music/tags.ts',
			'src/lib/widgets/music/tag-worker.ts',
			'**/*.test.ts'
		],
		rules: {
			'@typescript-eslint/no-restricted-imports': [
				'error',
				{
					paths: [{ name: 'music-metadata', allowTypeImports: true, message: MAIN_THREAD }],
					patterns: [{ regex: TAGS_MODULE, allowTypeImports: true, message: MAIN_THREAD }]
				}
			]
		}
	},
	{
		files: ['src/lib/widgets/music/tag-worker.ts'],
		rules: {
			'@typescript-eslint/no-restricted-imports': [
				'error',
				{ paths: [{ name: 'music-metadata', allowTypeImports: true, message: MAIN_THREAD }] }
			]
		}
	}
);
