import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vitest/config';
import { playwright } from '@vitest/browser-playwright';
import { sveltekit } from '@sveltejs/kit/vite';
import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

// Adapter, CSP, and compilerOptions live in svelte.config.js (doc 03 §Repo
// structure) so there is one place to look for framework configuration.
//
// No PWA plugin: the service worker is `src/service-worker.ts`, which SvelteKit
// compiles directly. Spike S5 explains why the plugin route was abandoned —
// see the header of that file and doc 22 §S5.

/**
 * `TP_BUILD` from doc 03 §Environment: version + short SHA, injected at build
 * time. The log ring buffer's boot line and the bug-report environment block
 * (doc 18 §1–2) both cite it, so a report can be pinned to a build.
 *
 * Three sources in order, because all three situations are real: Cloudflare
 * Workers Builds sets the env var and ships no `.git`; a local checkout has
 * git; a source tarball has neither.
 */
function buildInfo(): { version: string; sha: string } {
	const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
		version?: unknown;
	};
	const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';

	const fromCi = process.env['WORKERS_CI_COMMIT_SHA'] ?? process.env['CF_PAGES_COMMIT_SHA'];
	if (typeof fromCi === 'string' && fromCi.length > 0) {
		return { version, sha: fromCi.slice(0, 7) };
	}

	try {
		const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore']
		}).trim();
		if (sha.length > 0) return { version, sha };
	} catch {
		// No git, or not a repository. Fall through.
	}

	return { version, sha: 'dev' };
}

export default defineConfig({
	plugins: [
		// Before sveltekit(): the compiled output has to exist when SvelteKit
		// resolves $lib/paraglide imports.
		paraglideVitePlugin({
			project: './project.inlang',
			outdir: './src/lib/paraglide',
			// doc 14 §1. `url` is ruled out by that section; the built-in
			// `localStorage` strategy would create a fourth localStorage key, which
			// doc 05 §2 forbids — hence the custom one backed by the settings store.
			strategy: ['custom-tpsettings', 'preferredLanguage', 'baseLocale'],
			// Lets svelte-check read declarations instead of type-checking generated
			// JS under checkJs — which is what keeps `pnpm lint` clean given that the
			// output is gitignored and only exists after a compile.
			emitTsDeclarations: true
		}),
		tailwindcss(),
		sveltekit()
	],
	define: {
		__TP_BUILD__: JSON.stringify(buildInfo())
	},
	test: {
		expect: { requireAssertions: true },
		coverage: {
			provider: 'v8',
			reporter: ['text-summary', 'lcov'],
			include: ['src/lib/**/*.{ts,svelte}', 'src/routes/api/**/*.ts'],
			exclude: [
				'src/**/*.{test,spec}.{ts,js}',
				'src/**/__fixtures__/**',
				// Generated by paraglide-js at compile time.
				'src/lib/paraglide/**',
				// doc 19 §2: widget UI is component-tested but exempt from line
				// thresholds, because it churns; their service.ts files are not.
				'src/lib/widgets/**/Tp*.svelte',
				// doc 19 §2 carve-out. The grid's contract is an invariant across
				// fifty add/remove cycles — wrapper, host and tile counts agreeing —
				// which only e2e/s1-grid can express and line coverage cannot see.
				'src/lib/core/grid/**/*.svelte',
				// Same judgment doc 19 §2 already made for widget UI: shared chrome
				// is markup and wiring, covered by component tests and e2e for
				// behaviour. Line coverage of markup is weak signal, and the .ts
				// logic underneath stays inside the thresholds.
				'src/lib/ui/**/*.svelte',
				// Same doc 19 §2 reasoning as the grid: the contract is "registers,
				// activates, serves /offline, and never reloads under the user",
				// which e2e/s5-pwa asserts against a real service worker. A stubbed
				// unit test would check less and break more.
				'src/lib/core/pwa.svelte.ts',
				// Harnesses, not product.
				'src/routes/spike/**',
				// Week 0 spike code that landed in the real repo (doc 22 §Exit
				// review) ahead of the widgets that will use it. Each re-enters
				// with its consumer: charts in Week 4, the music library in Week 7.
				'src/lib/charts/**',
				'src/lib/widgets/music/**'
			],
			thresholds: {
				lines: 75,
				branches: 75,
				// doc 19 §2: branches sit at 80 because this tree is defensive by
				// design — fail-closed catch arms dominate the branch count.
				'src/lib/core/**': { lines: 90, branches: 80 },
				'src/lib/lunar/**': { lines: 90, branches: 80 },
				'src/routes/api/**': { lines: 85, branches: 85 }
			}
		},
		projects: [
			{
				extends: './vite.config.ts',
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						// Pinned, and load-bearing rather than tidy. Without it the
						// iframe a file renders into is sized by how many files happen
						// to be running beside it, so a centred detail panel can cover
						// the scrim's own corner — the exact geometry doc 19 §4's
						// corner-click rule exists to avoid. A suite whose layout
						// depends on its own file count fails on the run *after* the
						// one that added a file, which is the worst way to find out.
						viewport: { width: 1280, height: 800 },
						instances: [{ browser: 'chromium', headless: true }]
					},
					// Storage and <html> leak between component tests otherwise.
					setupFiles: ['./src/vitest-browser-setup.ts'],
					// doc 19 §1: component tests must carry the `.svelte.` infix or
					// they run in node and fail on DOM access.
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**']
				}
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
